name: Code Audit

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies b
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npmb-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npmb-

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
